FROM python:3.8

ARG ssh_prv_key
ARG ssh_pub_key

# Authorize SSH Host
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com > /root/.ssh/known_hosts

RUN python3 -m pip install -U pip

RUN echo "deb http://deb.debian.org/debian/ bullseye main contrib" >>  /etc/apt/sources.list && \
    echo "deb-src http://deb.debian.org/debian/ bullseye main contrib" >>  /etc/apt/sources.list

# Add locales 
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales tzdata

RUN sed -i -e 's/# es_CO.UTF-8 UTF-8/es_CO.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=es_CO.UTF-8

# Add dependencies
RUN pip install fastapi && \
   pip install uvicorn && \
   pip install Jinja2 && \
   pip install opencv-python-headless
   
ENV LANG es_CO.UTF-8
ENV TZ='America/Bogota'

WORKDIR /app_face_reco

# Production 
CMD ["uvicorn","app:app","--host", "0.0.0.0","--port","8590","--loop","asyncio","--workers=1","--reload"]